apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-inference-ingress
  namespace: ml-inference
spec:
  ingressClassName: nginx
  rules:
    - host: ml-inference.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-inference-service
                port:
                  number: 8000