apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
  namespace: ml-inference
spec:
  selector:
    app: ml-inference-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
